# Generated by Django 5.2.11 on 2026-02-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('section', models.CharField(choices=[('ESKOM', 'Eskom'), ('BOAT', 'Boat Club'), ('OWNER', 'Owner Managed'), ('PUBLIC', 'Public')], max_length=20)),
                ('approval_flow', models.CharField(choices=[('ESKOM_ADMIN', 'Eskom → Admin'), ('BOAT_ADMIN', 'Boat Club → Admin'), ('OWNER_ADMIN', 'Owner → Admin'), ('ADMIN_ONLY', 'Admin Only')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
