# Generated by Django 5.2.12 on 2026-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0002_stand_is_member_owned_stand_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='notes',
        ),
        migrations.AlterField(
            model_name='stand',
            name='approval_flow',
            field=models.CharField(choices=[('ADMIN_ONLY', 'Admin Only'), ('ESKOM_ADMIN', 'Eskom → Admin'), ('BOAT_ADMIN', 'Boat Club → Admin'), ('OWNER_ADMIN', 'Owner → Admin')], default='ADMIN_ONLY', max_length=30),
        ),
    ]
