# Generated by Django 5.2.12 on 2026-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='cell_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='membership_expiry',
            new_name='membership_expiry_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='call_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('B', 'Junior Boys (<19)'), ('L', 'Senior Ladies (19-49)'), ('O', 'Masters Men (50+)'), ('G', 'Junior Girls (<19)'), ('M', 'Senior Men (19-49)'), ('T', 'Masters Ladies (50+)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='initials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('GUEST', 'Guest'), ('EXPIRED', 'Expired Member')], default='GUEST', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='savof_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
