# Generated by Django 5.2.12 on 2026-03-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_phone_profile_cell_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_number',
            new_name='ID_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('B', 'B Junior Boys (<19)'), ('L', 'L Senior Ladies (19-49)'), ('O', 'O Masters Men (50+)'), ('G', 'G Junior Girls (<19)'), ('M', 'M Senior Men (19-49)'), ('T', 'T Masters Ladies (50+)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SOCIAL MEMBER', 'Social Member'), ('GUEST', 'Guest'), ('UNPAID', 'Unpaid Member'), ('EXPIRED', 'Expired Member')], default='GUEST', max_length=20),
        ),
    ]
