# Generated by Django 5.2.12 on 2026-03-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_id_number_profile_id_number_and_more'),
        ('stands', '0003_remove_stand_is_active_remove_stand_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owned_stand',
            field=models.ForeignKey(blank=True, help_text='Stand owned by this member (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stands.stand'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('O', 'O Men Masters (50+)'), ('M', 'M Men Senior (19-49)'), ('B', 'B Boys Junior (<19)'), ('T', 'T Ladies Masters (50+)'), ('L', 'L Ladies Senior (19-49)'), ('G', 'G Girls Junior (<19)')], max_length=1, null=True),
        ),
    ]
