# Generated by Django 5.2.12 on 2026-03-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_owned_stand_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membership_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SOCIAL MEMBER', 'Social Member'), ('GUEST', 'Guest'), ('UNPAID', 'Unpaid Member'), ('EXPIRED', 'Expired Member'), ('ESKOM MEMBER', 'Eskom Member'), ('UNPAID ESKOM', 'Unpaid Eskom Member'), ('BOAT CLUB MEMBER', 'Boat Club Member')], default='GUEST', max_length=20),
        ),
    ]
