# Generated by Django 5.2.11 on 2026-02-26 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_datetime', models.DateTimeField()),
                ('departure_datetime', models.DateTimeField()),
                ('booking_mode', models.CharField(choices=[('STRICT', 'Group Booking (All or Nothing)'), ('FLEXIBLE', 'Flexible Booking')], default='FLEXIBLE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('PARTIAL', 'Partially Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('QUOTE', 'Quote'), ('CONFIRMED', 'Confirmed Amount'), ('PAID', 'Paid at Gate'), ('REFUSED', 'Refused / Denied Entry')], default='QUOTE', max_length=20)),
                ('attendance_status', models.CharField(choices=[('NOT_ARRIVED', 'Not Arrived'), ('CHECKED_IN', 'Checked In'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled Before Arrival')], default='NOT_ARRIVED', max_length=20)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('non_member_adult_count', models.PositiveIntegerField(default=0)),
                ('child_count', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_nights', models.PositiveIntegerField(default=0)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('override_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stands.stand')),
            ],
            options={
                'unique_together': {('booking', 'stand')},
            },
        ),
    ]
