# Generated by Django 5.2.11 on 2026-03-01 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingstand',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookingstand',
            name='action_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='attendance_status',
            field=models.CharField(default='NOT_ARRIVED', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_mode',
            field=models.CharField(default='STANDARD', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='non_member_adult_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='QUOTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingstand',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('AWAITING_MEMBER_ACTION', 'Awaiting Member Action'), ('REJECTED', 'Rejected'), ('OVERRIDDEN', 'Overridden')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingstand',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_stands', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='bookingstand',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_bookings', to='stands.stand'),
        ),
        migrations.RemoveField(
            model_name='bookingstand',
            name='rejection_reason',
        ),
    ]
