# Generated by Django 5.2.11 on 2026-03-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingstand_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
