# Generated by Django 5.2.12 on 2026-03-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingstandaudit_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstand',
            name='stand',
        ),
        migrations.AddField(
            model_name='bookingstand',
            name='stand_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='attendance_status',
            field=models.CharField(default='CREATED', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingstand',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('READY_FOR_GATE', 'Ready For Gate')], default='PENDING', max_length=30),
        ),
    ]
