# Generated by Django 5.2.12 on 2026-03-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_bookingstand_stand_bookingstand_stand_number_and_more'),
        ('stands', '0002_stand_is_member_owned_stand_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstand',
            name='stand_number',
        ),
        migrations.AddField(
            model_name='bookingstand',
            name='stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stands.stand'),
        ),
    ]
