# Generated by Django 5.2.12 on 2026-03-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_bookingstand_stand_number_bookingstand_stand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attendance_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_mode',
            field=models.CharField(choices=[('ADMIN', 'Admin Captured'), ('REQUEST', 'Member Request'), ('WALKIN', 'Walk-in')], default='ADMIN', max_length=20),
        ),
    ]
