# Generated by Django 5.2.12 on 2026-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_guest_email_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstand',
            name='unavailable_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingstand',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Booked'), ('REJECTED', 'Refused Booking'), ('READY_FOR_GATE', 'Booking Approved'), ('UNAVAILABLE', 'Unavailable')], default='PENDING', max_length=30),
        ),
    ]
